### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by cindy-1999** [BDBC-KG-NLP/AAAI2022_ContrastNet#2]
Dear Author:
Thanks for providing the code, but I had faced some issues about the VRAM of GPU.
I try to find out where can I adjust the hyperparameter of batch-size to handle this issue.
However, It seems there is no options for main.py to control the parameter. Could you give me some suggestion!

Thank you.

**Comment by AlbertChen1991** [comment]
You may need 40GB GPU or at least 32GB GPU availble to train ContrastNet on the Amazon, Reuters and 20News datasets especially in 5-way 5-shot setting, because their sentence are much longer. As we undate the parameters per episode, there are no hyper-parameters to control the batch size. You may use less unlabeled texts and tasks for unspervised contrastive learning  or use shorter max-length of the sentence to reduce the memory needed. However, this may degrade the model performance.
